name: bmi_calculator
description: Simple BMI calculator for adults.
version: 2.0.0+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
     sdk: flutter
  google_fonts: ^1.0.0
  shared_preferences: ^0.5.7
  rxdart: ^0.24.0
  get_it: ^4.0.2
  flutter_svg: ^0.17.4
  toast: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4


flutter_icons:
  android: 'launcher_icon'
  ios: false
  image_path: "assets/bmi.png" 
  adaptive_icon_background: "#ffffff"
  

flutter:
  uses-material-design: true

  assets:
    - assets/
    - lang/



